### API 1
GET http://localhost:3000/players/

### API 2
GET http://localhost:3000/players/2/

### API 3
 PUT http://localhost:3000/players/2/
Content-Type: application/json

{
  "playerName": "Raju"
}

### API 4
GET http://localhost:3000/matches/2/

### API 5
GET http://localhost:3000/players/2/matches

### API 6
GET http://localhost:3000/matches/2/players

### API 7
GET http://localhost:3000/players/1/playerScores

